import type { ToolName } from './tool-definitions.js';

/**
 * How a tool reaches the Godot engine (or does not).
 *
 * - `process`: owns or inspects a Godot editor/game process launched by the server.
 * - `subprocess`: dispatches one operation to src/scripts/godot_operations.gd via the CLI.
 * - `authoring-session`: sends a command to the persistent authoring loop and
 *   retains an explicit subprocess fallback until session parity is proven.
 * - `runtime`: sends one JSON-RPC command to the in-game runtime server over TCP.
 * - `runtime-buffer`: reads output buffered from the runtime connection without a command.
 * - `godot-cli`: invokes the Godot executable directly (version, --check-only, export).
 * - `local`: implemented in TypeScript against the project files and configuration.
 */
export type ToolBackend =
  | { readonly kind: 'process' }
  | { readonly kind: 'subprocess'; readonly operation: string }
  | {
    readonly kind: 'authoring-session';
    readonly command: string;
    readonly fallback: { readonly kind: 'subprocess'; readonly operation: string };
  }
  | { readonly kind: 'runtime'; readonly command: string }
  | { readonly kind: 'runtime-buffer' }
  | { readonly kind: 'godot-cli' }
  | { readonly kind: 'local' };

export interface ToolManifestEntry {
  /** Owning handler class, mirrored from domain-tool-registries.ts. */
  readonly domain: 'lifecycle' | 'project' | 'game';
  /** Handler method dispatched by the domain registry. */
  readonly handler: string;
  readonly backend: ToolBackend;
  /**
   * Every public action the tool accepts, or null for single-action tools.
   * Cross-checked against schema enums, GDScript action declarations, and
   * handler dispatch by tests/tool-manifest.test.ts so a new action cannot
   * ship without appearing here (and in the coverage inventory).
   */
  readonly actions: readonly string[] | null;
  /** True when the schema's `action` field is data (an InputMap action name), not a mode selector. */
  readonly actionParamIsData?: true;
  /** True when the downstream runtime command requires the privileged-commands capability. */
  readonly privileged: boolean;
}

/**
 * Machine-readable traceability manifest: one entry per advertised MCP tool.
 * The Record key type makes completeness and uniqueness a compile-time fact,
 * and tests/tool-manifest.test.ts verifies every mapping against the sources.
 */
export const toolManifest: Record<ToolName, ToolManifestEntry> = {
  launch_editor: {
    domain: 'lifecycle',
    handler: 'handleLaunchEditor',
    backend: { kind: 'process' },
    actions: null,
    privileged: false,
  },
  editor_control: {
    domain: 'lifecycle',
    handler: 'handleEditorControl',
    backend: { kind: 'process' },
    actions: ['inspect', 'select', 'save', 'reload', 'open_scene', 'set_property', 'rename_node', 'undo', 'redo'],
    privileged: false,
  },
  run_project: {
    domain: 'lifecycle',
    handler: 'handleRunProject',
    backend: { kind: 'process' },
    actions: null,
    privileged: false,
  },
  verify_project: {
    domain: 'lifecycle',
    handler: 'handleVerifyProject',
    backend: { kind: 'process' },
    actions: null,
    privileged: false,
  },
  run_project_tests: {
    domain: 'project',
    handler: 'handleRunProjectTests',
    backend: { kind: 'godot-cli' },
    actions: ['discover', 'run'],
    privileged: false,
  },
  manage_import_pipeline: {
    domain: 'project',
    handler: 'handleManageImportPipeline',
    backend: { kind: 'godot-cli' },
    actions: ['inspect', 'change', 'reimport', 'dependencies'],
    privileged: false,
  },
  analyze_project_integrity: {
    domain: 'project',
    handler: 'handleAnalyzeProjectIntegrity',
    backend: { kind: 'local' },
    actions: ['analyze', 'preview_rename', 'assets', 'localization', 'accessibility', 'extensions', 'leaks'],
    privileged: false,
  },
  verify_export_readiness: {
    domain: 'project',
    handler: 'handleVerifyExportReadiness',
    backend: { kind: 'godot-cli' },
    actions: ['inspect', 'export_smoke'],
    privileged: false,
  },
  verify_dotnet_project: {
    domain: 'project',
    handler: 'handleVerifyDotnetProject',
    backend: { kind: 'godot-cli' },
    actions: ['inspect', 'restore', 'build', 'run'],
    privileged: false,
  },
  manage_addon: {
    domain: 'project',
    handler: 'handleManageAddon',
    backend: { kind: 'godot-cli' },
    actions: ['inspect', 'install', 'update', 'remove', 'enable', 'disable'],
    privileged: false,
  },
  get_debug_output: {
    domain: 'lifecycle',
    handler: 'handleGetDebugOutput',
    backend: { kind: 'process' },
    actions: null,
    privileged: false,
  },
  stop_project: {
    domain: 'lifecycle',
    handler: 'handleStopProject',
    backend: { kind: 'process' },
    actions: null,
    privileged: false,
  },
  get_godot_version: {
    domain: 'lifecycle',
    handler: 'handleGetGodotVersion',
    backend: { kind: 'process' },
    actions: null,
    privileged: false,
  },
  list_projects: {
    domain: 'project',
    handler: 'handleListProjects',
    backend: { kind: 'local' },
    actions: null,
    privileged: false,
  },
  get_project_info: {
    domain: 'project',
    handler: 'handleGetProjectInfo',
    backend: { kind: 'godot-cli' },
    actions: null,
    privileged: false,
  },
  create_scene: {
    domain: 'project',
    handler: 'handleCreateScene',
    backend: { kind: 'authoring-session', command: 'authoring_create_scene', fallback: { kind: 'subprocess', operation: 'create_scene' } },
    actions: null,
    privileged: false,
  },
  add_node: {
    domain: 'project',
    handler: 'handleAddNode',
    backend: { kind: 'authoring-session', command: 'authoring_add_node', fallback: { kind: 'subprocess', operation: 'add_node' } },
    actions: null,
    privileged: false,
  },
  load_sprite: {
    domain: 'project',
    handler: 'handleLoadSprite',
    backend: { kind: 'authoring-session', command: 'authoring_load_sprite', fallback: { kind: 'subprocess', operation: 'load_sprite' } },
    actions: null,
    privileged: false,
  },
  export_mesh_library: {
    domain: 'project',
    handler: 'handleExportMeshLibrary',
    backend: { kind: 'authoring-session', command: 'authoring_export_mesh_library', fallback: { kind: 'subprocess', operation: 'export_mesh_library' } },
    actions: null,
    privileged: false,
  },
  save_scene: {
    domain: 'project',
    handler: 'handleSaveScene',
    backend: { kind: 'authoring-session', command: 'authoring_save_scene', fallback: { kind: 'subprocess', operation: 'save_scene' } },
    actions: null,
    privileged: false,
  },
  get_uid: {
    domain: 'project',
    handler: 'handleGetUid',
    backend: { kind: 'authoring-session', command: 'authoring_get_uid', fallback: { kind: 'subprocess', operation: 'get_uid' } },
    actions: null,
    privileged: false,
  },
  update_project_uids: {
    domain: 'project',
    handler: 'handleUpdateProjectUids',
    backend: { kind: 'authoring-session', command: 'authoring_resave_resources', fallback: { kind: 'subprocess', operation: 'resave_resources' } },
    actions: null,
    privileged: false,
  },
  game_screenshot: {
    domain: 'game',
    handler: 'handleGameScreenshot',
    backend: { kind: 'runtime', command: 'screenshot' },
    actions: null,
    privileged: false,
  },
  game_visual_regression: {
    domain: 'game',
    handler: 'handleGameVisualRegression',
    backend: { kind: 'local' },
    actions: ['capture_baseline', 'compare'],
    privileged: false,
  },
  game_click: {
    domain: 'game',
    handler: 'handleGameClick',
    backend: { kind: 'runtime', command: 'click' },
    actions: null,
    privileged: false,
  },
  game_key_press: {
    domain: 'game',
    handler: 'handleGameKeyPress',
    backend: { kind: 'runtime', command: 'key_press' },
    actions: null,
    actionParamIsData: true,
    privileged: false,
  },
  game_mouse_move: {
    domain: 'game',
    handler: 'handleGameMouseMove',
    backend: { kind: 'runtime', command: 'mouse_move' },
    actions: null,
    privileged: false,
  },
  game_get_ui: {
    domain: 'game',
    handler: 'handleGameGetUi',
    backend: { kind: 'runtime', command: 'get_ui_elements' },
    actions: null,
    privileged: false,
  },
  game_get_scene_tree: {
    domain: 'game',
    handler: 'handleGameGetSceneTree',
    backend: { kind: 'runtime', command: 'get_scene_tree' },
    actions: null,
    privileged: false,
  },
  game_eval: {
    domain: 'game',
    handler: 'handleGameEval',
    backend: { kind: 'runtime', command: 'eval' },
    actions: null,
    privileged: true,
  },
  game_get_property: {
    domain: 'game',
    handler: 'handleGameGetProperty',
    backend: { kind: 'runtime', command: 'get_property' },
    actions: null,
    privileged: true,
  },
  game_set_property: {
    domain: 'game',
    handler: 'handleGameSetProperty',
    backend: { kind: 'runtime', command: 'set_property' },
    actions: null,
    privileged: true,
  },
  game_call_method: {
    domain: 'game',
    handler: 'handleGameCallMethod',
    backend: { kind: 'runtime', command: 'call_method' },
    actions: null,
    privileged: true,
  },
  game_get_node_info: {
    domain: 'game',
    handler: 'handleGameGetNodeInfo',
    backend: { kind: 'runtime', command: 'get_node_info' },
    actions: null,
    privileged: false,
  },
  game_instantiate_scene: {
    domain: 'game',
    handler: 'handleGameInstantiateScene',
    backend: { kind: 'runtime', command: 'instantiate_scene' },
    actions: null,
    privileged: false,
  },
  game_remove_node: {
    domain: 'game',
    handler: 'handleGameRemoveNode',
    backend: { kind: 'runtime', command: 'remove_node' },
    actions: null,
    privileged: false,
  },
  game_change_scene: {
    domain: 'game',
    handler: 'handleGameChangeScene',
    backend: { kind: 'runtime', command: 'change_scene' },
    actions: null,
    privileged: false,
  },
  game_pause: {
    domain: 'game',
    handler: 'handleGamePause',
    backend: { kind: 'runtime', command: 'pause' },
    actions: null,
    privileged: false,
  },
  game_performance: {
    domain: 'game',
    handler: 'handleGamePerformance',
    backend: { kind: 'runtime', command: 'get_performance' },
    actions: ['sample', 'start', 'stop', 'report', 'leaks'],
    privileged: false,
  },
  game_wait: {
    domain: 'game',
    handler: 'handleGameWait',
    backend: { kind: 'runtime', command: 'wait' },
    actions: null,
    privileged: false,
  },
  read_scene: {
    domain: 'project',
    handler: 'handleReadScene',
    backend: { kind: 'authoring-session', command: 'authoring_read_scene', fallback: { kind: 'subprocess', operation: 'read_scene' } },
    actions: null,
    privileged: false,
  },
  modify_scene_node: {
    domain: 'project',
    handler: 'handleModifySceneNode',
    backend: { kind: 'authoring-session', command: 'authoring_modify_node', fallback: { kind: 'subprocess', operation: 'modify_node' } },
    actions: null,
    privileged: false,
  },
  remove_scene_node: {
    domain: 'project',
    handler: 'handleRemoveSceneNode',
    backend: { kind: 'authoring-session', command: 'authoring_remove_node', fallback: { kind: 'subprocess', operation: 'remove_node' } },
    actions: null,
    privileged: false,
  },
  read_project_settings: {
    domain: 'project',
    handler: 'handleReadProjectSettings',
    backend: { kind: 'local' },
    actions: null,
    privileged: false,
  },
  modify_project_settings: {
    domain: 'project',
    handler: 'handleModifyProjectSettings',
    backend: { kind: 'local' },
    actions: null,
    privileged: false,
  },
  list_project_files: {
    domain: 'project',
    handler: 'handleListProjectFiles',
    backend: { kind: 'local' },
    actions: null,
    privileged: false,
  },
  game_connect_signal: {
    domain: 'game',
    handler: 'handleGameConnectSignal',
    backend: { kind: 'runtime', command: 'connect_signal' },
    actions: null,
    privileged: false,
  },
  game_disconnect_signal: {
    domain: 'game',
    handler: 'handleGameDisconnectSignal',
    backend: { kind: 'runtime', command: 'disconnect_signal' },
    actions: null,
    privileged: false,
  },
  game_emit_signal: {
    domain: 'game',
    handler: 'handleGameEmitSignal',
    backend: { kind: 'runtime', command: 'emit_signal' },
    actions: null,
    privileged: false,
  },
  game_play_animation: {
    domain: 'game',
    handler: 'handleGamePlayAnimation',
    backend: { kind: 'runtime', command: 'play_animation' },
    actions: ['play', 'stop', 'pause', 'get_list'],
    privileged: false,
  },
  game_tween_property: {
    domain: 'game',
    handler: 'handleGameTweenProperty',
    backend: { kind: 'runtime', command: 'tween_property' },
    actions: null,
    privileged: false,
  },
  game_get_nodes_in_group: {
    domain: 'game',
    handler: 'handleGameGetNodesInGroup',
    backend: { kind: 'runtime', command: 'get_nodes_in_group' },
    actions: null,
    privileged: false,
  },
  game_find_nodes_by_class: {
    domain: 'game',
    handler: 'handleGameFindNodesByClass',
    backend: { kind: 'runtime', command: 'find_nodes_by_class' },
    actions: null,
    privileged: false,
  },
  game_reparent_node: {
    domain: 'game',
    handler: 'handleGameReparentNode',
    backend: { kind: 'runtime', command: 'reparent_node' },
    actions: null,
    privileged: false,
  },
  attach_script: {
    domain: 'project',
    handler: 'handleAttachScript',
    backend: { kind: 'authoring-session', command: 'authoring_attach_script', fallback: { kind: 'subprocess', operation: 'attach_script' } },
    actions: null,
    privileged: false,
  },
  create_resource: {
    domain: 'project',
    handler: 'handleCreateResource',
    backend: { kind: 'authoring-session', command: 'authoring_create_resource', fallback: { kind: 'subprocess', operation: 'create_resource' } },
    actions: null,
    privileged: false,
  },
  read_file: {
    domain: 'project',
    handler: 'handleReadFile',
    backend: { kind: 'local' },
    actions: null,
    privileged: false,
  },
  write_file: {
    domain: 'project',
    handler: 'handleWriteFile',
    backend: { kind: 'local' },
    actions: null,
    privileged: false,
  },
  delete_file: {
    domain: 'project',
    handler: 'handleDeleteFile',
    backend: { kind: 'local' },
    actions: null,
    privileged: false,
  },
  create_directory: {
    domain: 'project',
    handler: 'handleCreateDirectory',
    backend: { kind: 'local' },
    actions: null,
    privileged: false,
  },
  game_get_errors: {
    domain: 'game',
    handler: 'handleGameGetErrors',
    backend: { kind: 'runtime-buffer' },
    actions: null,
    privileged: false,
  },
  game_get_logs: {
    domain: 'game',
    handler: 'handleGameGetLogs',
    backend: { kind: 'runtime-buffer' },
    actions: null,
    privileged: false,
  },
  game_key_hold: {
    domain: 'game',
    handler: 'handleGameKeyHold',
    backend: { kind: 'runtime', command: 'key_hold' },
    actions: null,
    actionParamIsData: true,
    privileged: false,
  },
  game_key_release: {
    domain: 'game',
    handler: 'handleGameKeyRelease',
    backend: { kind: 'runtime', command: 'key_release' },
    actions: null,
    actionParamIsData: true,
    privileged: false,
  },
  game_scroll: {
    domain: 'game',
    handler: 'handleGameScroll',
    backend: { kind: 'runtime', command: 'scroll' },
    actions: null,
    privileged: false,
  },
  game_mouse_drag: {
    domain: 'game',
    handler: 'handleGameMouseDrag',
    backend: { kind: 'runtime', command: 'mouse_drag' },
    actions: null,
    privileged: false,
  },
  game_gamepad: {
    domain: 'game',
    handler: 'handleGameGamepad',
    backend: { kind: 'runtime', command: 'gamepad' },
    actions: null,
    privileged: false,
  },
  create_project: {
    domain: 'project',
    handler: 'handleCreateProject',
    backend: { kind: 'local' },
    actions: null,
    privileged: false,
  },
  create_csharp_script: {
    domain: 'project',
    handler: 'handleCreateCsharpScript',
    backend: { kind: 'local' },
    actions: null,
    privileged: false,
  },
  manage_autoloads: {
    domain: 'project',
    handler: 'handleManageAutoloads',
    backend: { kind: 'local' },
    actions: ['list', 'add', 'remove'],
    privileged: false,
  },
  manage_input_map: {
    domain: 'project',
    handler: 'handleManageInputMap',
    backend: { kind: 'local' },
    actions: ['list', 'add', 'remove'],
    privileged: false,
  },
  manage_export_presets: {
    domain: 'project',
    handler: 'handleManageExportPresets',
    backend: { kind: 'local' },
    actions: ['list', 'add', 'remove'],
    privileged: false,
  },
  game_get_camera: {
    domain: 'game',
    handler: 'handleGameGetCamera',
    backend: { kind: 'runtime', command: 'get_camera' },
    actions: null,
    privileged: false,
  },
  game_set_camera: {
    domain: 'game',
    handler: 'handleGameSetCamera',
    backend: { kind: 'runtime', command: 'set_camera' },
    actions: null,
    privileged: false,
  },
  game_raycast: {
    domain: 'game',
    handler: 'handleGameRaycast',
    backend: { kind: 'runtime', command: 'raycast' },
    actions: null,
    privileged: false,
  },
  game_get_audio: {
    domain: 'game',
    handler: 'handleGameGetAudio',
    backend: { kind: 'runtime', command: 'get_audio' },
    actions: null,
    privileged: false,
  },
  game_spawn_node: {
    domain: 'game',
    handler: 'handleGameSpawnNode',
    backend: { kind: 'runtime', command: 'spawn_node' },
    actions: null,
    privileged: false,
  },
  game_set_shader_param: {
    domain: 'game',
    handler: 'handleGameSetShaderParam',
    backend: { kind: 'runtime', command: 'set_shader_param' },
    actions: null,
    privileged: false,
  },
  game_audio_play: {
    domain: 'game',
    handler: 'handleGameAudioPlay',
    backend: { kind: 'runtime', command: 'audio_play' },
    actions: ['play', 'stop', 'pause', 'resume'],
    privileged: false,
  },
  game_audio_bus: {
    domain: 'game',
    handler: 'handleGameAudioBus',
    backend: { kind: 'runtime', command: 'audio_bus' },
    actions: null,
    privileged: false,
  },
  game_navigate_path: {
    domain: 'game',
    handler: 'handleGameNavigatePath',
    backend: { kind: 'runtime', command: 'navigate_path' },
    actions: null,
    privileged: false,
  },
  game_tilemap: {
    domain: 'game',
    handler: 'handleGameTilemap',
    backend: { kind: 'runtime', command: 'tilemap' },
    actions: ['set_cells', 'get_cell', 'erase_cells', 'get_used_cells'],
    privileged: false,
  },
  game_add_collision: {
    domain: 'game',
    handler: 'handleGameAddCollision',
    backend: { kind: 'runtime', command: 'add_collision' },
    actions: null,
    privileged: false,
  },
  game_environment: {
    domain: 'game',
    handler: 'handleGameEnvironment',
    backend: { kind: 'runtime', command: 'environment' },
    actions: ['get', 'set'],
    privileged: false,
  },
  game_manage_group: {
    domain: 'game',
    handler: 'handleGameManageGroup',
    backend: { kind: 'runtime', command: 'manage_group' },
    actions: ['add', 'remove', 'get_groups'],
    privileged: false,
  },
  game_create_timer: {
    domain: 'game',
    handler: 'handleGameCreateTimer',
    backend: { kind: 'runtime', command: 'create_timer' },
    actions: null,
    privileged: false,
  },
  game_set_particles: {
    domain: 'game',
    handler: 'handleGameSetParticles',
    backend: { kind: 'runtime', command: 'set_particles' },
    actions: null,
    privileged: false,
  },
  game_create_animation: {
    domain: 'game',
    handler: 'handleGameCreateAnimation',
    backend: { kind: 'runtime', command: 'create_animation' },
    actions: null,
    privileged: false,
  },
  export_project: {
    domain: 'project',
    handler: 'handleExportProject',
    backend: { kind: 'godot-cli' },
    actions: null,
    privileged: false,
  },
  game_serialize_state: {
    domain: 'game',
    handler: 'handleGameSerializeState',
    backend: { kind: 'runtime', command: 'serialize_state' },
    actions: ['save', 'load'],
    privileged: false,
  },
  game_physics_body: {
    domain: 'game',
    handler: 'handleGamePhysicsBody',
    backend: { kind: 'runtime', command: 'physics_body' },
    actions: null,
    privileged: false,
  },
  game_create_joint: {
    domain: 'game',
    handler: 'handleGameCreateJoint',
    backend: { kind: 'runtime', command: 'create_joint' },
    actions: null,
    privileged: false,
  },
  game_bone_pose: {
    domain: 'game',
    handler: 'handleGameBonePose',
    backend: { kind: 'runtime', command: 'bone_pose' },
    actions: ['list', 'get', 'set'],
    privileged: false,
  },
  game_ui_theme: {
    domain: 'game',
    handler: 'handleGameUiTheme',
    backend: { kind: 'runtime', command: 'ui_theme' },
    actions: null,
    privileged: false,
  },
  game_viewport: {
    domain: 'game',
    handler: 'handleGameViewport',
    backend: { kind: 'runtime', command: 'viewport' },
    actions: ['create', 'configure', 'get'],
    privileged: false,
  },
  game_debug_draw: {
    domain: 'game',
    handler: 'handleGameDebugDraw',
    backend: { kind: 'runtime', command: 'debug_draw' },
    actions: ['line', 'sphere', 'box', 'clear'],
    privileged: false,
  },
  game_http_request: {
    domain: 'game',
    handler: 'handleGameHttpRequest',
    backend: { kind: 'runtime', command: 'http_request' },
    actions: null,
    privileged: true,
  },
  game_websocket: {
    domain: 'game',
    handler: 'handleGameWebsocket',
    backend: { kind: 'runtime', command: 'websocket' },
    actions: ['connect', 'disconnect', 'send', 'receive', 'status'],
    privileged: true,
  },
  game_multiplayer: {
    domain: 'game',
    handler: 'handleGameMultiplayer',
    backend: { kind: 'runtime', command: 'multiplayer' },
    actions: ['create_server', 'create_client', 'disconnect', 'status'],
    privileged: false,
  },
  game_rpc: {
    domain: 'game',
    handler: 'handleGameRpc',
    backend: { kind: 'runtime', command: 'rpc' },
    actions: ['call', 'configure'],
    privileged: true,
  },
  game_touch: {
    domain: 'game',
    handler: 'handleGameTouch',
    backend: { kind: 'runtime', command: 'touch' },
    actions: ['press', 'release', 'drag'],
    privileged: false,
  },
  game_input_state: {
    domain: 'game',
    handler: 'handleGameInputState',
    backend: { kind: 'runtime', command: 'input_state' },
    actions: ['query', 'warp_mouse', 'set_mouse_mode'],
    privileged: false,
  },
  game_input_action: {
    domain: 'game',
    handler: 'handleGameInputAction',
    backend: { kind: 'runtime', command: 'input_action' },
    actions: ['set_strength', 'add_action', 'remove_action', 'list'],
    privileged: false,
  },
  game_list_signals: {
    domain: 'game',
    handler: 'handleGameListSignals',
    backend: { kind: 'runtime', command: 'list_signals' },
    actions: null,
    privileged: false,
  },
  game_await_signal: {
    domain: 'game',
    handler: 'handleGameAwaitSignal',
    backend: { kind: 'runtime', command: 'await_signal' },
    actions: null,
    privileged: false,
  },
  game_script: {
    domain: 'game',
    handler: 'handleGameScript',
    backend: { kind: 'runtime', command: 'script' },
    actions: ['get_source', 'attach', 'detach'],
    privileged: true,
  },
  game_window: {
    domain: 'game',
    handler: 'handleGameWindow',
    backend: { kind: 'runtime', command: 'window' },
    actions: ['get', 'set'],
    privileged: false,
  },
  game_os_info: {
    domain: 'game',
    handler: 'handleGameOsInfo',
    backend: { kind: 'runtime', command: 'os_info' },
    actions: null,
    privileged: false,
  },
  game_time_scale: {
    domain: 'game',
    handler: 'handleGameTimeScale',
    backend: { kind: 'runtime', command: 'time_scale' },
    actions: ['get', 'set'],
    privileged: false,
  },
  game_process_mode: {
    domain: 'game',
    handler: 'handleGameProcessMode',
    backend: { kind: 'runtime', command: 'process_mode' },
    actions: null,
    privileged: false,
  },
  game_world_settings: {
    domain: 'game',
    handler: 'handleGameWorldSettings',
    backend: { kind: 'runtime', command: 'world_settings' },
    actions: ['get', 'set'],
    privileged: false,
  },
  game_csg: {
    domain: 'game',
    handler: 'handleGameCsg',
    backend: { kind: 'runtime', command: 'csg' },
    actions: ['create', 'configure'],
    privileged: false,
  },
  game_multimesh: {
    domain: 'game',
    handler: 'handleGameMultimesh',
    backend: { kind: 'runtime', command: 'multimesh' },
    actions: ['create', 'set_instance', 'get_info'],
    privileged: false,
  },
  game_procedural_mesh: {
    domain: 'game',
    handler: 'handleGameProceduralMesh',
    backend: { kind: 'runtime', command: 'procedural_mesh' },
    actions: null,
    privileged: false,
  },
  game_light_3d: {
    domain: 'game',
    handler: 'handleGameLight3d',
    backend: { kind: 'runtime', command: 'light_3d' },
    actions: ['create', 'configure'],
    privileged: false,
  },
  game_mesh_instance: {
    domain: 'game',
    handler: 'handleGameMeshInstance',
    backend: { kind: 'runtime', command: 'mesh_instance' },
    actions: null,
    privileged: false,
  },
  game_gridmap: {
    domain: 'game',
    handler: 'handleGameGridmap',
    backend: { kind: 'runtime', command: 'gridmap' },
    actions: ['set_cell', 'get_cell', 'clear', 'get_used'],
    privileged: false,
  },
  game_3d_effects: {
    domain: 'game',
    handler: 'handleGame3dEffects',
    backend: { kind: 'runtime', command: '3d_effects' },
    actions: null,
    privileged: false,
  },
  game_gi: {
    domain: 'game',
    handler: 'handleGameGi',
    backend: { kind: 'runtime', command: 'gi' },
    actions: null,
    privileged: false,
  },
  game_path_3d: {
    domain: 'game',
    handler: 'handleGamePath3d',
    backend: { kind: 'runtime', command: 'path_3d' },
    actions: ['create', 'add_point', 'get_points', 'set_points'],
    privileged: false,
  },
  game_sky: {
    domain: 'game',
    handler: 'handleGameSky',
    backend: { kind: 'runtime', command: 'sky' },
    actions: ['create'],
    privileged: false,
  },
  game_camera_attributes: {
    domain: 'game',
    handler: 'handleGameCameraAttributes',
    backend: { kind: 'runtime', command: 'camera_attributes' },
    actions: ['get', 'set'],
    privileged: false,
  },
  game_navigation_3d: {
    domain: 'game',
    handler: 'handleGameNavigation3d',
    backend: { kind: 'runtime', command: 'navigation_3d' },
    actions: ['create', 'bake'],
    privileged: false,
  },
  game_physics_3d: {
    domain: 'game',
    handler: 'handleGamePhysics3d',
    backend: { kind: 'runtime', command: 'physics_3d' },
    actions: ['ray', 'overlap', 'contacts', 'inspect_shape'],
    privileged: false,
  },
  game_canvas: {
    domain: 'game',
    handler: 'handleGameCanvas',
    backend: { kind: 'runtime', command: 'canvas' },
    actions: ['create_layer', 'create_modulate', 'configure'],
    privileged: false,
  },
  game_canvas_draw: {
    domain: 'game',
    handler: 'handleGameCanvasDraw',
    backend: { kind: 'runtime', command: 'canvas_draw' },
    actions: ['line', 'rect', 'circle', 'polygon', 'text', 'clear'],
    privileged: false,
  },
  game_light_2d: {
    domain: 'game',
    handler: 'handleGameLight2d',
    backend: { kind: 'runtime', command: 'light_2d' },
    actions: ['create_point', 'create_directional', 'create_occluder'],
    privileged: false,
  },
  game_parallax: {
    domain: 'game',
    handler: 'handleGameParallax',
    backend: { kind: 'runtime', command: 'parallax' },
    actions: ['create_background', 'add_layer', 'configure'],
    privileged: false,
  },
  game_shape_2d: {
    domain: 'game',
    handler: 'handleGameShape2d',
    backend: { kind: 'runtime', command: 'shape_2d' },
    actions: ['add_point', 'set_points', 'clear', 'get_points'],
    privileged: false,
  },
  game_path_2d: {
    domain: 'game',
    handler: 'handleGamePath2d',
    backend: { kind: 'runtime', command: 'path_2d' },
    actions: ['create', 'add_point', 'get_points'],
    privileged: false,
  },
  game_physics_2d: {
    domain: 'game',
    handler: 'handleGamePhysics2d',
    backend: { kind: 'runtime', command: 'physics_2d' },
    actions: ['ray', 'overlap', 'point_query', 'shape_query'],
    privileged: false,
  },
  game_animation_tree: {
    domain: 'game',
    handler: 'handleGameAnimationTree',
    backend: { kind: 'runtime', command: 'animation_tree' },
    actions: ['travel', 'set_param', 'get_state'],
    privileged: false,
  },
  game_animation_control: {
    domain: 'game',
    handler: 'handleGameAnimationControl',
    backend: { kind: 'runtime', command: 'animation_control' },
    actions: ['seek', 'queue', 'set_speed', 'stop', 'get_info'],
    privileged: false,
  },
  game_skeleton_ik: {
    domain: 'game',
    handler: 'handleGameSkeletonIk',
    backend: { kind: 'runtime', command: 'skeleton_ik' },
    actions: ['start', 'stop', 'set_target'],
    privileged: false,
  },
  game_audio_effect: {
    domain: 'game',
    handler: 'handleGameAudioEffect',
    backend: { kind: 'runtime', command: 'audio_effect' },
    actions: ['list', 'add', 'remove', 'configure'],
    privileged: false,
  },
  game_audio_bus_layout: {
    domain: 'game',
    handler: 'handleGameAudioBusLayout',
    backend: { kind: 'runtime', command: 'audio_bus_layout' },
    actions: ['list', 'add', 'remove', 'move', 'set_send'],
    privileged: false,
  },
  game_audio_spatial: {
    domain: 'game',
    handler: 'handleGameAudioSpatial',
    backend: { kind: 'runtime', command: 'audio_spatial' },
    actions: ['get_info', 'configure'],
    privileged: false,
  },
  rename_file: {
    domain: 'project',
    handler: 'handleRenameFile',
    backend: { kind: 'local' },
    actions: null,
    privileged: false,
  },
  manage_resource: {
    domain: 'project',
    handler: 'handleManageResource',
    backend: { kind: 'authoring-session', command: 'authoring_manage_resource', fallback: { kind: 'subprocess', operation: 'manage_resource' } },
    actions: ['read', 'modify'],
    privileged: false,
  },
  validate_script: {
    domain: 'project',
    handler: 'handleValidateScript',
    backend: { kind: 'godot-cli' },
    actions: null,
    privileged: false,
  },
  validate_scripts: {
    domain: 'project',
    handler: 'handleValidateScripts',
    backend: { kind: 'godot-cli' },
    actions: null,
    privileged: false,
  },
  create_script: {
    domain: 'project',
    handler: 'handleCreateScript',
    backend: { kind: 'local' },
    actions: null,
    privileged: false,
  },
  manage_scene_signals: {
    domain: 'project',
    handler: 'handleManageSceneSignals',
    backend: { kind: 'authoring-session', command: 'authoring_manage_scene_signals', fallback: { kind: 'subprocess', operation: 'manage_scene_signals' } },
    actions: ['list', 'add', 'remove'],
    privileged: false,
  },
  manage_layers: {
    domain: 'project',
    handler: 'handleManageLayers',
    backend: { kind: 'local' },
    actions: ['list', 'set'],
    privileged: false,
  },
  manage_plugins: {
    domain: 'project',
    handler: 'handleManagePlugins',
    backend: { kind: 'local' },
    actions: ['list', 'enable', 'disable'],
    privileged: false,
  },
  manage_shader: {
    domain: 'project',
    handler: 'handleManageShader',
    backend: { kind: 'local' },
    actions: ['read', 'create'],
    privileged: false,
  },
  manage_theme_resource: {
    domain: 'project',
    handler: 'handleManageThemeResource',
    backend: { kind: 'authoring-session', command: 'authoring_manage_theme_resource', fallback: { kind: 'subprocess', operation: 'manage_theme_resource' } },
    actions: ['create', 'read', 'modify'],
    privileged: false,
  },
  set_main_scene: {
    domain: 'project',
    handler: 'handleSetMainScene',
    backend: { kind: 'local' },
    actions: null,
    privileged: false,
  },
  manage_scene_structure: {
    domain: 'project',
    handler: 'handleManageSceneStructure',
    backend: { kind: 'authoring-session', command: 'authoring_manage_scene_structure', fallback: { kind: 'subprocess', operation: 'manage_scene_structure' } },
    actions: ['rename', 'duplicate', 'move'],
    privileged: false,
  },
  manage_translations: {
    domain: 'project',
    handler: 'handleManageTranslations',
    backend: { kind: 'local' },
    actions: ['list', 'add', 'remove'],
    privileged: false,
  },
  game_locale: {
    domain: 'game',
    handler: 'handleGameLocale',
    backend: { kind: 'runtime', command: 'locale' },
    actions: ['get', 'set', 'translate'],
    privileged: false,
  },
  game_ui_control: {
    domain: 'game',
    handler: 'handleGameUiControl',
    backend: { kind: 'runtime', command: 'ui_control' },
    actions: ['grab_focus', 'release_focus', 'configure', 'get_info'],
    privileged: false,
  },
  game_ui_text: {
    domain: 'game',
    handler: 'handleGameUiText',
    backend: { kind: 'runtime', command: 'ui_text' },
    actions: ['get', 'set', 'append', 'clear', 'bbcode'],
    privileged: false,
  },
  game_ui_popup: {
    domain: 'game',
    handler: 'handleGameUiPopup',
    backend: { kind: 'runtime', command: 'ui_popup' },
    actions: ['popup_centered', 'popup', 'hide', 'get_info'],
    privileged: false,
  },
  game_ui_tree: {
    domain: 'game',
    handler: 'handleGameUiTree',
    backend: { kind: 'runtime', command: 'ui_tree' },
    actions: ['get_items', 'add', 'select', 'collapse', 'expand', 'remove'],
    privileged: false,
  },
  game_ui_item_list: {
    domain: 'game',
    handler: 'handleGameUiItemList',
    backend: { kind: 'runtime', command: 'ui_item_list' },
    actions: ['get_items', 'select', 'add', 'remove', 'clear'],
    privileged: false,
  },
  game_ui_tabs: {
    domain: 'game',
    handler: 'handleGameUiTabs',
    backend: { kind: 'runtime', command: 'ui_tabs' },
    actions: ['get_tabs', 'set_current', 'set_title'],
    privileged: false,
  },
  game_ui_menu: {
    domain: 'game',
    handler: 'handleGameUiMenu',
    backend: { kind: 'runtime', command: 'ui_menu' },
    actions: ['get_items', 'add', 'remove', 'set_checked', 'clear'],
    privileged: false,
  },
  game_ui_range: {
    domain: 'game',
    handler: 'handleGameUiRange',
    backend: { kind: 'runtime', command: 'ui_range' },
    actions: ['get', 'set'],
    privileged: false,
  },
  game_render_settings: {
    domain: 'game',
    handler: 'handleGameRenderSettings',
    backend: { kind: 'runtime', command: 'render_settings' },
    actions: ['get', 'set'],
    privileged: false,
  },
  game_resource: {
    domain: 'game',
    handler: 'handleGameResource',
    backend: { kind: 'runtime', command: 'resource' },
    actions: ['load', 'preload', 'save', 'exists'],
    privileged: false,
  },
  game_visual_shader: {
    domain: 'game',
    handler: 'handleGameVisualShader',
    backend: { kind: 'runtime', command: 'visual_shader' },
    actions: ['create', 'add_node', 'connect', 'disconnect', 'get_nodes', 'apply'],
    privileged: false,
  },
  game_terrain: {
    domain: 'game',
    handler: 'handleGameTerrain',
    backend: { kind: 'runtime', command: 'terrain' },
    actions: ['create', 'get_height', 'modify', 'paint'],
    privileged: false,
  },
  game_video: {
    domain: 'game',
    handler: 'handleGameVideo',
    backend: { kind: 'runtime', command: 'video' },
    actions: ['create', 'play', 'pause', 'resume', 'stop', 'seek', 'get_status'],
    privileged: false,
  },
  manage_ci_pipeline: {
    domain: 'project',
    handler: 'handleManageCiPipeline',
    backend: { kind: 'local' },
    actions: ['create', 'read'],
    privileged: false,
  },
  manage_docker_export: {
    domain: 'project',
    handler: 'handleManageDockerExport',
    backend: { kind: 'local' },
    actions: ['create', 'read'],
    privileged: false,
  },
};

export type AuthoringSessionToolBackend = Extract<ToolBackend, { kind: 'authoring-session' }>;

const authoringBackendsByOperation = new Map<string, AuthoringSessionToolBackend>();
for (const entry of Object.values(toolManifest)) {
  if (entry.backend.kind !== 'authoring-session') continue;
  const operation = entry.backend.fallback.operation;
  if (authoringBackendsByOperation.has(operation)) {
    throw new Error(`Duplicate authoring operation backend: ${operation}`);
  }
  authoringBackendsByOperation.set(operation, entry.backend);
}

/** Resolves an operation through the public tool's declared backend policy. */
export function authoringBackendForOperation(operation: string): AuthoringSessionToolBackend | undefined {
  return authoringBackendsByOperation.get(operation);
}
